<p>Best Chance to Win is a trade name owned by EG Sports, LLC, which makes this Website, including any and all information, documents, communications, files, text, graphics, software, and audio/visual files (collectively, the "Service") available for your use subject to the Terms and Conditions of Use set forth below. Please read these terms and conditions carefully before using the Website, accessing the Content and/or using the Services. By using the Website, the Services, or the Content, you are consenting to the terms and conditions in this terms of service agreement as they apply to you and your usage and access. Your use of the Website, the Content, and the Services is also subject to all applicable laws and regulations. If you do not agree to any of the terms of service in this agreement (the "TOS"), you should not use the Website, the Services, or the Content. Your use of the Website, the Content, and the Services is also governed by our Privacy Policy, which is available through a link on our homepage as well as most of the other pages on the Website. 

<h2>1. TERMS OF SERVICE</h2>
<p>EG Sports, LLC provides the Website, the Content, and the Services to you subject to the following Terms of Service ("TOS"). The TOS may be updated by us from time to time without notice to you. We suggest that from time to time you review the TOS for possible changes. In addition, when using any Services or accessing any Content, you will be subject to any posted guidelines or rules applicable to such Services or Content. All such additional guidelines or rules are hereby incorporated by reference into the TOS.

<h2>2. SERVICES AND CONTENT</h2>
<p><?=ucfirst($maind)?> currently provides users with various features and services, including NFL picks, wager account and other interactive and non-interactive features, all of which may be updated, deleted, or otherwise modified from time to time at the discretion of <?=$maind?>. In addition, <?=$maind?> provides access to certain photographs, text, images, statistics, logos, and other media and intellectual property related to or otherwise associated with <?=$maind?>. Unless stated otherwise, the Website, the Services, and the Content are subject to the TOS. You understand and agree that the Website, the Services, and the Content are provided "AS IS" and that <?=$maind?> assumes no responsibility in connection with your use of the Website, the Services, or the Content. The Website, the Services, and the Content are provided for your non-commercial entertainment and enjoyment. Under the TOS, you may download certain Content and Services available on the Website to a single personal computing device for your use and entertainment. However, you may not distribute, modify, republish, or publicly display any of the Content or Services unless you have the prior written permission of <?=$maind?>, which permission may be withheld at <?=$maind?>'s sole discretion.

<h2>3. ACCESS TO SERVICES</h2>
<p>In order to use the Website or the Services or access the Content, you must obtain access to the World Wide Web and pay any service fees associated with such access. In addition, you must provide all equipment necessary to make such connection to the World Wide Web, including a computer and modem or other access device.

<h2>4. BACKGROUND INFORMATION</h2>
<p>In order to use the Services, you may be required to register with <?=$maind?> by providing certain information about yourself, including your name and email address. In consideration of your use of the Services, you agree to provide true, accurate, current and complete information about yourself as requested in connection with the provision of and/or registration for any of the Services, subject, of course, to all applicable laws. If you provide any information that is untrue, inaccurate, not current, or incomplete, or <?=$maind?> has reasonable grounds to suspect that such information is untrue, inaccurate, not current, or incomplete, <?=$maind?> has the right to suspend or terminate your password and/or refuse any and all current or future use of the Services.

<h2>5. ACCESS BY MINORS</h2>
<p>Persons under the age of 21 are prohibited from registering on <?=$maind?>.

<h2>6. PRIVACY POLICY</h2>
<p>All information collected about you during registration for use of the Services will be used in accordance with our Privacy Policy and all applicable laws.

<h2>7. MEMBER PASSWORD AND SECURITY</h2>
<p>You will receive a password upon completing the registration process for use of certain Services. You are responsible for maintaining the confidentiality of the password and are fully responsible for all activities that occur under your password. <?=ucfirst($maind)?> cannot and will not be liable for any loss or damage arising from your failure to comply with this Section 7.

<h2>8. MEMBER CONDUCT</h2>
<p>You agree that in connection with your use of the Website, the Services, and the Content you will not: a) upload, post, email or otherwise transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, libelous, invasive of anyone's privacy, hateful, or racially, ethnically or otherwise objectionable; b) harm or attempt to harm minors in any way; c) impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity; d) upload, post, email or otherwise transmit any content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); e) upload, post, email or otherwise transmit any content that infringes any patent, trademark, trade secret, copyright or other intellectual property right of any party; f) upload, post, email or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation; g) upload, post, email or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; h) interfere with or disrupt the Website, the Services, the Content or servers or networks connected to the Website, the Services or the Content, or disobey any requirements, procedures, policies or regulations of networks connected to the Website, the Services and/or the Content; i) intentionally or unintentionally violate any applicable local, state, national or international law.

<h2>9. USER MESSAGES</h2>
<p>a) With respect to any messages, information, data, graphics, photographs, images, creative ideas, concepts, know-how, techniques, suggestions or improvements or other content that you transmit, submit, post or upload to the Website and/or in connection with any of the Services (each, "Message"), you are, by transmitting or uploading such Message, granting <?=$maind?> a perpetual, royalty-free, sub-licensable, non-exclusive, worldwide and irrevocable right and license to use, reproduce, modify, publish, translate, prepare derivative works based upon, and distribute such Message for any purpose and in any form. This license is granted automatically and no payment of any kind will be due to you. At times, <?=$maind?> may solicit Messages from users. Your provision of any such Messages in response to a solicitation by <?=$maind?> shall be subject to a grant of a license to <?=$maind?> as specified above. b) When any user posts any Message to the Website or any of the Services, <?=$maind?> shall have the right, but not the obligation, to review, edit or delete any Message for any reason, at <?=$maind?>'s sole discretion. It is <?=$maind?>'s policy to fully cooperate with law enforcement authorities and court orders which request or require <?=$maind?> to disclose personal information or the postings of anyone posting Messages to the Website or any of the Services. Although <?=$maind?> may monitor and/or review Messages from time to time, it is under no obligation to do so and does not assume any liability or responsibility with respect to any Messages including those that contain errors, defamatory content, pornography, profanity or inaccuracies. c) You acknowledge and agree that <?=$maind?> may preserve Messages and may also disclose Messages if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (i) comply with legal process; (ii) enforce the TOS; (iii) respond to claims that any Message violates the rights of third-parties; or (iv) protect the rights, property, or personal safety of <?=$maind?>, its users and the public. You understand that the technical processing and transmission of the Services, including Messages, may involve a) transmissions over various networks; and b) changes to conform and adapt to technical requirements of connecting networks or devices.

<h2>10. TRADEMARKS</h2>
<p>Provider owns trademarks and service marks for its goods and services, including, without limitation, BEST CHANCE TO WIN and <?=strtoupper($maind)?> and the associated graphics, logos and service marks are trademarks of EG SPORTS, LLC  and may not be used without prior written consent of Provider. All other trademarks, product names, and company names and logos appearing on the Website are the property of their respective owners.

<h2>11. INDEMNITY</h2>
<p>You agree to indemnify, defend and hold harmless <?=$maind?> , the directors, governors, owners, other officials, partners, partnerships, principals, employees, affiliates and other related entities, servants, agents, representatives, successors and assigns from and against any claim or demand, including reasonable attorneys' fees, arising out of Messages you post to, submit or transmit through the Website or the Services, your use of the Website or the Services, your connection to the Website or the Services, your violation of the TOS, or your violation of any rights of another.

<h2>12. MODIFICATIONS TO WEBSITE, INCLUDING THE SERVICES</h2>
<p><?=ucfirst($maind)?> reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Website or Services (or any part thereof) with or without notice.

<h2>13. TERMINATION</h2>
<p>You agree that <?=$maind?>, in its sole discretion, may terminate your password or use of the Website and/or the Services, and remove and discard any Message within the Services, for any reason, including, without limitation, for lack of use or if <?=$maind?> believes that you have violated or acted inconsistently with the letter or spirit of the TOS. You agree that any termination of your access to the Services under any provision of this TOS may be effected without prior notice, and acknowledge and agree that <?=$maind?> may immediately deactivate or delete your password and all related information and/or files corresponding to your password and/or bar any further access to such files or the Services.

<h2>14. <?=strtoupper($maind)?> ADVERTISERS AND VENDORS</h2>
<p>Your correspondence or business dealings with, or participation in promotions of, advertisers and vendors found on or through the Services or the Website, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser and/or vendor. You agree that <?=$maind?> shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers or vendors on the Website or in connection with the Services. All of your business dealings with vendors and advertisers appearing on the Website or in connection with the Services shall be at your sole risk.

<h2>15. LINKING</h2>
<p>The Website and/or Services may provide, or third parties may provide, links to other World Wide Web sites or resources. Because <?=$maind?> has no control over such sites and resources, you acknowledge and agree that <?=$maind?> is not responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable for any content, advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that <?=$maind?> shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.

<h2>16. PROPRIETARY RIGHT</h2>
<p>Services and Content are the property of <?=$maind?> and are licensed to <?=$maind?> and may not be reproduced without the prior written consent of <?=$maind?>. You further acknowledge and agree that a) any necessary software used in connection with the Website, the Services, and the Content (the "Software") contains proprietary and confidential information that is protected by applicable intellectual property and other laws and are either owned by or licensed to <?=$maind?>; and b) content contained in sponsor advertisements or information presented to you through the Website, the Services, and the Content or advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by <?=$maind?> or advertisers, you agree not to reproduce, republish, upload, post, transmit, distribute, copy, publicly display or otherwise use any Content or any derivative works based on the Website, Services, Content or the Software, in whole or in part. You agree not to modify the Software in any manner or form, or to use modified versions of the Software, including (without limitation) for the purpose of obtaining unauthorized access to the Services. You agree not to access the Services by any means other than through the interface that is provided by <?=$maind?> for use in accessing the Services.

<h2>17. DISCLAIMER OF WARRANTIES</h2>
<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT: a) YOUR USE OF THE WEBSITE, THE SERVICES AND THE CONTENT IS AT YOUR SOLE RISK. THE WEBSITE, THE SERVICES AND THE CONTENT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. <?=strtoupper($maind)?> EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. b) <?=strtoupper($maind)?> MAKES NO WARRANTY THAT (i) THE WEBSITE, SERVICES OR THE CONTENT WILL MEET YOUR REQUIREMENTS, (ii) THE WEBSITE, THE SERVICES OR THE CONTENT WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM YOUR USE OF THE WEBSITE, THE SERVICES OR THE CONTENT WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE WEBSITE, THE SERVICES OR THE CONTENT WILL MEET YOUR EXPECTATIONS, AND (v) ANY ERRORS IN THE SOFTWARE OPERATING ON THE WEBSITE WILL BE CORRECTED. c) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITE OR THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE WEBSITE OR THROUGH OR FROM THE SERVICES OR THE CONTENT SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.

<h2>18. LIMITATION OF LIABILITY</h2>
<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT <?=strtoupper($maind)?> SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF <?=strtoupper($maind)?> HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE WEBSITE, THE SERVICES, OR THE CONTENT; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE WEBSITE, THE SERVICES, OR THE CONTENT; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE WEBSITE, THE SERVICES, OR IN THE CONTENT; OR (v) ANY OTHER MATTER RELATING TO THE WEBSITE, THE SERVICES, OR THE CONTENT.

<h2>19. EXCLUSIONS AND LIMITATIONS</h2>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS OF SECTIONS 17 AND 18 MAY NOT APPLY TO YOU.

<h2>20. NOTICE</h2>
<p>Notices to you may be made via either email or regular mail. The Website may also provide notices of changes to the TOS or other matters by displaying notices or links to notices to you generally on the Services.

<h2>21. LINKING TO THE WEBSITE</h2>
<p>No link to the Website may be "framed" to the extent such frame contains any sponsorship, advertising, or other commercial text or graphics.

<h2>22. GENERAL PROVISIONS</h2>
<p>The TOS constitute the entire agreement between you and <?=$maind?> and governs your use of the Website, the Services, and access to the Content, superseding any prior agreements between you and <?=$maind?>. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third-party content or third-party software. The Website is created and controlled by EG Sports, LLC in the State of Illinois. As such, the laws of the State of Illinois will govern these disclaimers, terms and conditions, without giving effect to any principles of conflicts of laws. EG Sports, LLC reserves the right to make changes to its Website and these disclaimers, terms and conditions at any time. The failure of <?=$maind?> to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision. User hereby irrevocably and unconditionally consents to submit to the jurisdiction of the State of Illinois for any litigation arising out of or relating to use of or purchase made through the Website (and agrees not to commence any litigation relating thereto except in such courts), waives any objection to the laying of venue of any such litigation in the Illinois courts and agrees not to plead or claim in any Illinois court that such litigation brought therein has been brought in an inconvenient forum. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or the TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the TOS are for convenience only and have no legal or contractual effect.

<h2>23. Entire Agreement</h2>
<p>These Terms and Conditions of Use constitute the entire agreement between the User and Provider with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. Any waiver of any provision of the Terms and Conditions of Use or Privacy Policy will be effective only if in writing and signed by Provider.

<p><b>THE SECTION TITLES IN THE TERMS OF USE ARE FOR CONVENIENCE ONLY AND HAVE NO LEGAL OR CONTRACTUAL EFFECT.</b></p>

<div class="infoc">Date Last Modified:  March 24, 2018</div>

<p>These Terms and Conditions of Use may be changed at any time, without prior notice.</p>
<p>Activities offered by advertising links to other sites may be deemed an illegal activity in certain jurisdictions. Viewers are specifically warned that they should inquire into the legality of participating in any games and/or activities offered by such other sites. The owner of this website assumes no responsibility for the actions by and makes no representation or endorsement of any of these games and/or activities offered by the advertiser. As a condition of viewing this website viewers agree to hold the owner of this website harmless from any claims arising from the viewer's participation in any of the games and/or activities offered by the advertiser.</p>
<p>US CITIZENS PLEASE NOTE: The information contained at this site is for news and entertainment purposes only. Any use of this information in violation of any federal, state, provincial or local law is prohibited.</p>
