<img src="/img/money-management.jpg" class="img1r" />
<h2>Money Management</h2>
<p>There are two elements to successful wagering. The first is making the picks which this site will do for you. The second is correct money management which you must do for yourself. It is a common mistake to focus on the first element when both are equally important. If either is lacking, then luck becomes the controlling factor since even a winning season will have periodic losing weekends.</p>
<p>Here's why money management is so critical. If all of the season’s wagers were made in one day, money management would be obvious since the bankroll would be safely split among many games. With the bets being laid out several at a time over 17 weeks, a trap is set for the unsophisticated bettor.</p>
<p>The initial challenge is to overcome the illusion that money management is self-evident or that winning will take care of it. At all costs, you must resist the urge of thinking "This game is a sure thing". The wager must remain the same correct amount per game, no matter what the previous weekend or current season record turns out to be.</p>
<p>A money management scheme must address two issues. The first is to preserve the bankroll particularly at the outset of the season so that one or two losing weeks do not prematurely end an entire season. Then, once winnings are in hand, it should allow them to grow at the most optimum rate. We recommend use of one of these schemes:</p>
<ul>
	<li>Determine an amount that can and will be wagered per game throughout the entire season, win or lose. For example, wager $100 per game only if you can commit to wagering this amount through the entire season, particularly the first couple of weeks regardless of outcome. This strategy makes more sense where money is not a strict issue.</li>
	<li>Set a bankroll for the season and wager the same appropriate percentage of it each game, win or lose. To determine the bankroll amount, a good start is to ask yourself: "How much could I lose in a single season on NFL wagering without worrying". Once the amount of the bankroll is set, then wager the correct percentage per game. There is a recommended guideline referred to as the Kelly system. To simplify for now and until you are playing with winnings, limit your wager to a more conservative 5% per game.</li>
</ul>
<p>The above is simple advice but very difficult to put into practice. The ability to actually do so separates the winners from the losers, at least for our customers. Hopefully, you won't have to learn the hard way.</p>